### 07/05/25

In [7]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Satish',np.nan],
     'Age':[np.nan,22,23,24],
     'City':['pune','hyd',np.nan,'blr']}
df=pd.DataFrame(Data)
df

Names   Age  City
0  Ramesh   NaN  pune
1  Suresh  22.0   hyd
2  Satish  23.0   NaN
3     NaN  24.0   blr

In [2]:
df.to_csv('data_missing.csv',index=False)

In [3]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Satish',None],
     'Age':[None,22,23,24],
     'City':['pune','hyd',None,'blr']}
df1=pd.DataFrame(Data)
df1

Names   Age  City
0  Ramesh   NaN  pune
1  Suresh  22.0   hyd
2  Satish  23.0  None
3    None  24.0   blr

In [4]:
df1.to_csv('data_missing.csv',index=False)

In [5]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

In [6]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

In [8]:
df.isnull()

Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [9]:
df1.isnull()

Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [10]:
df.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [11]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

**fillna**

In [12]:
df.fillna(30)  # not recomonded

Names   Age  City
0  Ramesh  30.0  pune
1  Suresh  22.0   hyd
2  Satish  23.0    30
3      30  24.0   blr

- The above one is we are filling randomly
- All the columns are filled with random number
- It is not a good approach because in a data we have different data types

In [13]:
df.fillna('Hyd')

Names   Age  City
0  Ramesh   Hyd  pune
1  Suresh  22.0   hyd
2  Satish  23.0   Hyd
3     Hyd  24.0   blr

In [14]:
df1.fillna('Hyd')

Names   Age  City
0  Ramesh   Hyd  pune
1  Suresh  22.0   hyd
2  Satish  23.0   Hyd
3     Hyd  24.0   blr

**What is the difference between np.nan and None**

In [14]:
np.nan+5

nan

In [15]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [16]:
arr1=np.array([1,2,np.nan,3])
arr2=np.array([1,2,None,3])

In [17]:
arr1

array([ 1.,  2., nan,  3.])

In [18]:
arr2

array([1, 2, None, 3], dtype=object)

In [19]:
np.sum(arr1)

nan

In [20]:
np.nansum(arr1)

6.0

In [21]:
np.sum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

- np.nan represents **float type**
- None represents **object type**
- If data operations related to Maths then nan format is better

**Fill the value based on column**

In [22]:
# df.fillna()
df['Names'].fillna('Manish')

0    Ramesh
1    Suresh
2    Satish
3    Manish
Name: Names, dtype: object

In [23]:
df

Names   Age  City
0  Ramesh   NaN  pune
1  Suresh  22.0   hyd
2  Satish  23.0   NaN
3     NaN  24.0   blr

In [15]:
df['Age'].fillna(20)

0    20.0
1    22.0
2    23.0
3    24.0
Name: Age, dtype: float64

In [16]:
df['Age'].fillna('20')

0      20
1    22.0
2    23.0
3    24.0
Name: Age, dtype: object

In [17]:
df['Age'].fillna(20).values

array([20., 22., 23., 24.])

In [18]:
df['Age'].fillna('20').values

array(['20', 22.0, 23.0, 24.0], dtype=object)

In [19]:
df['Age1']=df['Age'].fillna(20).values
df['Age2']=df['Age'].fillna('20').values

In [20]:
df

Names   Age  City  Age1  Age2
0  Ramesh   NaN  pune  20.0    20
1  Suresh  22.0   hyd  22.0  22.0
2  Satish  23.0   NaN  23.0  23.0
3     NaN  24.0   blr  24.0  24.0

In [21]:
df.dtypes

Names     object
Age      float64
City      object
Age1     float64
Age2      object
dtype: object

- Because of one value total data type is changed
- We can convert one data type column to another data type astype

In [22]:
df['Age2']=df['Age2'].astype('float')

In [23]:
df.dtypes

Names     object
Age      float64
City      object
Age1     float64
Age2     float64
dtype: object

**Fill with the methods**
- pad
- bfill
- ffill
- backfill

In [24]:
s='U+200B (ZERO WIDTH SPACE)'
s1=''
for i in s:
    if i.isdigit():
        s1=s1+i

int(s1)

200

In [28]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad')

Names   Age  City
0  Ramesh   NaN  pune
1  Suresh  22.0   hyd
2  Satish  23.0   hyd
3  Satish  24.0   blr

In [29]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='bfill')

Names   Age  City
0  Ramesh  22.0  pune
1  Suresh  22.0   hyd
2  Satish  23.0   blr
3     NaN  24.0   blr

In [30]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='ffill')

Names   Age  City
0  Ramesh   NaN  pune
1  Suresh  22.0   hyd
2  Satish  23.0   hyd
3  Satish  24.0   blr

In [31]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='backfill')

Names   Age  City
0  Ramesh  22.0  pune
1  Suresh  22.0   hyd
2  Satish  23.0   blr
3     NaN  24.0   blr

In [33]:
df.fillna(method='pad',axis=1)

Names     Age  City
0  Ramesh  Ramesh  pune
1  Suresh    22.0   hyd
2  Satish    23.0  23.0
3     NaN    24.0   blr

In [34]:
df.fillna(method='bfill',axis=1)

Names   Age  City
0  Ramesh  pune  pune
1  Suresh  22.0   hyd
2  Satish  23.0   NaN
3    24.0  24.0   blr

In [35]:
df.fillna(method='ffill',axis=1)

Names     Age  City
0  Ramesh  Ramesh  pune
1  Suresh    22.0   hyd
2  Satish    23.0  23.0
3     NaN    24.0   blr

In [36]:
df.fillna(method='backfill',axis=1)

Names   Age  City
0  Ramesh  pune  pune
1  Suresh  22.0   hyd
2  Satish  23.0   NaN
3    24.0  24.0   blr

### 08/05/25

In [ ]:
# idea-1: filling with random value= df.fillname(<random value>)
# idea-2: filling with rv based on column= df[<col>].fillname(<random value>)
# idea-3: filling with some pattern using a method: df.fillname(<method>)
# idea-4: filling with m-m-m based on column=df[<col>].fillna(<m>or<m>or<m>)
# idea-5: filling with avg value only selected neighbours

**Mean-Median-Mode**
- Instead of filling with random values
- We can use mean median and mode also
- For Numerical columns use Mean and Median
   - if Data outliers are there use **Median**
- For categorical columns are **Mode**

In [9]:
age_mean=df['Age'].mean()
print('Age_mean:',age_mean)
df['Age'].fillna(age_mean)

Age_mean: 23.0


0    23.0
1    22.0
2    23.0
3    24.0
Name: Age, dtype: float64

In [10]:
city_mode=df['City'].mode()
df['City'].fillna(city_mode)

0    pune
1     hyd
2    pune
3     blr
Name: City, dtype: object

In [25]:
# First calculate median
# Then fill with median
age_median=df['Age'].median()
df['Age'].fillna(age_median)

0    23.0
1    22.0
2    23.0
3    24.0
Name: Age, dtype: float64

In [11]:
age_mean # fixed

23.0

In [12]:
city_mode # series

0     blr
1     hyd
2    pune
Name: City, dtype: object

In [13]:
city_mode.values

array(['blr', 'hyd', 'pune'], dtype=object)

In [14]:
city_mode.values[0]

'blr'

In [26]:
round(df['Age'].mean(),2)

23.0

- in future sometimes if we direct impute mode value we will get error
- mode is coming as series
- mean is coming as fixed value
- so first convert series to fixed value then apply it

**impute class**
- under sklearn we have inpute class is there

In [16]:
from sklearn import impute

In [17]:
dir(impute)

['KNNImputer',
 'MissingIndicator',
 'SimpleImputer',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_knn',
 'typing']

**KNNlmputer**
- KNN: K nearest neighbours
- where k= hyper parameter which means the user can change
- Idea: instead of taking all the samples  average
  - firt fix the neighbours number i.e k
  - Then find the neighbours using distance metric
  - Then take the average of those samples to fill the missing value
- we can take only specific values average
- thats why the name is called as Nearest Neighbours
- Hyper parameter: the argument which user can provide
- here k is hyper parameter
- which means the user can decide how many neighbours he can choose
- it is under **sklearn**
  - class name **imputer**
    - method name **KNNlmputer**

In [27]:
data1={'A':[1,2,3,4,5,np.nan,7],
      'B':[11,22,np.nan,47,55,77,7],
      'C':[21,10,3,4,np.nan,66,7]}
df2=pd.DataFrame(data1)

In [28]:
from sklearn.impute import KNNImputer
knn=KNNImputer(n_neighbors=2)
knn.fit_transform(df2)

array([[ 1. , 11. , 21. ],
       [ 2. , 22. , 10. ],
       [ 3. , 51. ,  3. ],
       [ 4. , 47. ,  4. ],
       [ 5. , 55. ,  3.5],
       [ 4.5, 77. , 66. ],
       [ 7. ,  7. ,  7. ]])

In [29]:
(4+5+7)/3

5.333333333333333

In [30]:
(1+2+7)/3

3.3333333333333335

- How it is deciding neighbours: Euclidian distance
- Give the catagorical data: It is works or not 

In [18]:
import numpy as np
from sklearn.impute import KNNImputer

In [19]:
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(X)

0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [21]:
import numpy as np
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2,weights='distance')
imputer.fit_transform(X)

array([[ 1.        ,  2.        ,  3.93905505],
       [ 3.        , 31.        ,  3.        ],
       [ 3.25775362, 60.        ,  5.        ],
       [ 8.        ,  8.        ,  7.        ]])

In [ ]:
- weights='uniform'

In [22]:
import numpy as np
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2)
imputer.fit_transform(X)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

In [ ]:
# idea-1: filling with random value= df.fillname(<random value>)
# idea-2: filling with rv based on column= df[<col>].fillname(<random value>)
# idea-3: filling with some pattern using a method: df.fillname(<method>)
# idea-4: filling with m-m-m based on column=df[<col>].fillna(<m>or<m>or<m>)
# idea-5: filling with avg value only selected neighbours
# idea-6: filling with a value based on correlation with another columns